
on:
  push:
    branches:
      - main
      - dev
jobs:
  branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Update Branch Protection
        uses: Briqz23/branch-protection@v2
        with:
          require-review: true
          required-review-count: 1
          require-status-checks: true