#name: Branch Protection

#on:
#  push:
#    branches:
#      - main
#      - dev
      
#jobs:
#  branch-protection:
#    runs-on: ubuntu-latest
#    steps:
#     - name: Checkout Code
#       uses: actions/checkout@v2
#     - name: Update Branch Protection
#       uses: Raynnerz/Notebook-PI/main/.github/workflows/branch-protection.yml
#        #raynnerz/.github/tree/undefined/workflows/branch-protection
#        #Raynnerz/Notebook-PI/blob/main/.github/workflows/branch-protection.yml
#       with:
#          require-review: true
#         required-review-count: 1
#          require-status-checks: true